In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('2020-12-22.csv',index_col=[0])

In [6]:
df.iloc[:,33:]

            es          ds         ts  ms   ms_prob              match
0    73.687400   75.952020  149.66284   2  0.689733       Anadolu Efes
1    77.160620   76.467834  152.93988   1  0.601847              Zenit
2    69.973380   78.501915  150.51732   2  0.909818       Anadolu Efes
3    84.769226   73.356120  159.36661   2  0.559873        M. Tel Aviv
4    74.059740   80.863464  154.40282   2  0.786993              Asvel
5    90.038710   80.319370  169.15417   1  0.962329        Real Madrid
6    79.632960   72.263220  150.38605   1  0.963829     Virtus Bologna
7    89.189860   74.993650  162.82681   1  0.974112           Nanterre
8    85.480710   87.049340  172.38417   2  0.953056        Szombathely
9    73.379830   85.467410  163.38680   2  0.997495          Peristeri
10   86.426094   81.821230  169.53730   1  0.998054             Igokea
11   91.553240   81.160220  173.90442   1  0.986510        Darüşşafaka
12   87.339750   75.396790  165.56955   1  0.998710      Enel Brindisi
13   90.530970   85.752144  174.50002   1  0.916155             Málaga
14   81.757420   77.852350  159.38486   1  0.584201       Gran Canaria
15   74.690470   65.371950  140.84328   1  0.999486       Bourg Basket
16   78.511860   88.224250  165.99990   2  0.917562        Chemnitz 99
17   90.471560   76.396560  167.81447   1  0.988451         Crailsheim
18   80.521545   76.438934  157.11719   2  0.609712      Medi Bayreuth
20   76.675186   71.804690  145.65710   1  0.949955            Melilla
21   80.123040   69.147080  148.99335   1  0.886536       Leyma Coruna
22   68.649470   86.219850  155.95323   2  0.981554       Penas Huesca
23   81.215300   73.651720  153.90327   1  0.923632  Bahia San Agustin
24   79.905460   72.010450  153.18372   1  0.698053     Amics Castello
25   79.122680   67.388405  145.96090   1  0.542352          Fundacion
26   69.878300   78.506615  149.49239   2  0.734227            Almansa
32   81.093575   76.749756  155.83012   1  0.959601      Pato Basquete
33   79.132126   74.692200  154.45317   2  0.735492           C Mourao
34   93.363540   70.253610  160.61717   1  0.999732           Flamengo
37   71.449745   80.690315  150.92052   2  0.805497     Comunicaciones
38   84.306680   87.891090  173.93633   2  0.608783           Libertad
39   74.952420   65.675766  143.27450   1  0.679643         Corrientes
40   73.241270   81.961500  152.78716   2  0.932952              Obera
41   77.659520   76.350555  152.23158   2  0.654300             Quimsa
42   68.388910   84.372894  155.30269   2  0.955234             Atenas
43   87.520355   83.219444  172.04230   1  0.921688          Instituto
44   64.832110   87.753670  152.16388   2  0.997022            Triglav
45   84.909090   68.311264  154.02098   1  0.990007            Spisska
46   83.610435   75.889490  154.99971   1  0.713770         Iskra Svit
50   60.922390   76.342180  140.13065   2  0.911334         Valladolid
51   75.409850   70.250320  146.08495   1  0.820427            Clavijo
52   78.216900   73.850850  154.85437   1  0.993424             Estela
53   73.827484   74.645650  146.55675   1  0.807247             Zamora
54   76.785510   74.723210  153.33840   1  0.985030               UDEA
55   78.909065   71.275740  150.59892   1  0.991776         Alcobendas
56   73.818870   61.147896  134.86261   1  0.986504     Al Qazeres (K)
57   58.086407   66.985310  131.94313   2  0.904877       Bembibre (K)
58   69.845220   62.674650  131.73172   1  0.854028     UNI Girona (K)
59   61.954884   82.056630  141.13611   2  0.989597        Promete (K)
60   85.454520   57.512848  140.40186   1  0.996889       Valencia (K)
61   69.121000   64.579185  135.25047   1  0.821485       Clarinos (K)
62   71.859190   61.900494  132.40448   1  0.979652     Alcobendas (K)
64   70.817220   54.554420  128.13304   1  0.855212       Pruszków (K)
66   61.169952   59.390316  123.15232   2  0.861460          Beira Mar
67   89.182330   66.747170  153.75055   1  0.995801            Imortal
69   84.340965   67.092910  151.40950   1  0.932596        Dynamo MGTU
70   85.926810   68.997850  153.16104   1  0.997931             Tambov
72   65.767650   68.573960  130.75214   1  0.742234        Maribor (K)
73  111.467650  108.136345  221.30939   1  0.975167           Brooklyn

In [10]:
msler = df.sort_values(['ms_prob'],ascending=False).iloc[:,33:]

In [11]:
msler

            es          ds         ts  ms   ms_prob              match
34   93.363540   70.253610  160.61717   1  0.999732           Flamengo
15   74.690470   65.371950  140.84328   1  0.999486       Bourg Basket
12   87.339750   75.396790  165.56955   1  0.998710      Enel Brindisi
10   86.426094   81.821230  169.53730   1  0.998054             Igokea
70   85.926810   68.997850  153.16104   1  0.997931             Tambov
9    73.379830   85.467410  163.38680   2  0.997495          Peristeri
44   64.832110   87.753670  152.16388   2  0.997022            Triglav
60   85.454520   57.512848  140.40186   1  0.996889       Valencia (K)
67   89.182330   66.747170  153.75055   1  0.995801            Imortal
52   78.216900   73.850850  154.85437   1  0.993424             Estela
55   78.909065   71.275740  150.59892   1  0.991776         Alcobendas
45   84.909090   68.311264  154.02098   1  0.990007            Spisska
59   61.954884   82.056630  141.13611   2  0.989597        Promete (K)
17   90.471560   76.396560  167.81447   1  0.988451         Crailsheim
11   91.553240   81.160220  173.90442   1  0.986510        Darüşşafaka
56   73.818870   61.147896  134.86261   1  0.986504     Al Qazeres (K)
54   76.785510   74.723210  153.33840   1  0.985030               UDEA
22   68.649470   86.219850  155.95323   2  0.981554       Penas Huesca
62   71.859190   61.900494  132.40448   1  0.979652     Alcobendas (K)
73  111.467650  108.136345  221.30939   1  0.975167           Brooklyn
7    89.189860   74.993650  162.82681   1  0.974112           Nanterre
6    79.632960   72.263220  150.38605   1  0.963829     Virtus Bologna
5    90.038710   80.319370  169.15417   1  0.962329        Real Madrid
32   81.093575   76.749756  155.83012   1  0.959601      Pato Basquete
42   68.388910   84.372894  155.30269   2  0.955234             Atenas
8    85.480710   87.049340  172.38417   2  0.953056        Szombathely
20   76.675186   71.804690  145.65710   1  0.949955            Melilla
40   73.241270   81.961500  152.78716   2  0.932952              Obera
69   84.340965   67.092910  151.40950   1  0.932596        Dynamo MGTU
23   81.215300   73.651720  153.90327   1  0.923632  Bahia San Agustin
43   87.520355   83.219444  172.04230   1  0.921688          Instituto
16   78.511860   88.224250  165.99990   2  0.917562        Chemnitz 99
13   90.530970   85.752144  174.50002   1  0.916155             Málaga
50   60.922390   76.342180  140.13065   2  0.911334         Valladolid
2    69.973380   78.501915  150.51732   2  0.909818       Anadolu Efes
57   58.086407   66.985310  131.94313   2  0.904877       Bembibre (K)
21   80.123040   69.147080  148.99335   1  0.886536       Leyma Coruna
66   61.169952   59.390316  123.15232   2  0.861460          Beira Mar
64   70.817220   54.554420  128.13304   1  0.855212       Pruszków (K)
58   69.845220   62.674650  131.73172   1  0.854028     UNI Girona (K)
61   69.121000   64.579185  135.25047   1  0.821485       Clarinos (K)
51   75.409850   70.250320  146.08495   1  0.820427            Clavijo
53   73.827484   74.645650  146.55675   1  0.807247             Zamora
37   71.449745   80.690315  150.92052   2  0.805497     Comunicaciones
4    74.059740   80.863464  154.40282   2  0.786993              Asvel
72   65.767650   68.573960  130.75214   1  0.742234        Maribor (K)
33   79.132126   74.692200  154.45317   2  0.735492           C Mourao
26   69.878300   78.506615  149.49239   2  0.734227            Almansa
46   83.610435   75.889490  154.99971   1  0.713770         Iskra Svit
24   79.905460   72.010450  153.18372   1  0.698053     Amics Castello
0    73.687400   75.952020  149.66284   2  0.689733       Anadolu Efes
39   74.952420   65.675766  143.27450   1  0.679643         Corrientes
41   77.659520   76.350555  152.23158   2  0.654300             Quimsa
18   80.521545   76.438934  157.11719   2  0.609712      Medi Bayreuth
38   84.306680   87.891090  173.93633   2  0.608783           Libertad
1    77.160620   76.467834  152.93988   1  0.601847              Zenit
14   81.757420   77.852350  159.38486   1  0.584201       Gran Canaria
3    84.769226   73.356120  159.36661   2  0.559873        M. Tel Aviv
25   79.122680   67.388405  145.96090   1  0.542352          Fundacion

In [41]:
df[df.match.str.contains('')].iloc[:,33:]

          es         ds         ts  ms   ms_prob          match
9   73.37983  85.467410  163.38680   2  0.997495      Peristeri
12  87.33975  75.396790  165.56955   1  0.998710  Enel Brindisi
45  84.90909  68.311264  154.02098   1  0.990007        Spisska

In [32]:

from scipy.stats import binom

In [33]:
n = 3
p = 0.9

In [34]:
rv = binom(n,p)

In [36]:
 1- (rv.pmf(2)+rv.pmf(3))

0.028000000000000025

In [37]:
rv.pmf(2)

0.2429999999999999

In [38]:
rv.pmf(3)

0.7290000000000001